name: Run Backend Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Create .env file
        run: |
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" > .env

      - name: Start Server
        run: npm start &

      - name: Wait for server to be ready
        run: sleep 10

      - name: Install Newman (Postman CLI)
        run: npm install -g newman

      - name: Run Postman Tests
        run: newman run ../cargo/src/__tests_/Test-Collection.postman_collection.json --delay-request 1000 --timeout-request 10000
