name: Frontend CI
# This workflow runs frontend tests, ESLint, npm audit, and builds the project on every push to the main branch and on pull requests.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: cargo 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci 

      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx
      
      - name: Run npm audit
        run: npm audit --audit-level=high

      - name: Run unit tests
        run: npm test

      - name: Build project
        run: npm run build

      - name: Start frontend server
        run: npm run preview &
        env:
          NODE_ENV: development
          PORT: 4173

      - name: Wait for frontend to be ready
        run: npx wait-on http://localhost:4173

      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            http://localhost:4173/
          uploadArtifacts: true
          temporaryPublicStorage: true

      


